const { withGradleProperties } = require('expo/config-plugins');

/**
 * Build `armeabi-v7a` only: the target TCL set has no other ABI, and a
 * universal APK is 93 MB against 29 MB (measured). A plugin because
 * `android/gradle.properties` is regenerated by `expo prebuild`.
 */
const withArmV7aOnly = (config) =>
  withGradleProperties(config, (config) => {
    const properties = config.modResults;
    const key = 'reactNativeArchitectures';
    const existing = properties.find((item) => item.type === 'property' && item.key === key);

    if (existing) {
      existing.value = 'armeabi-v7a';
      return config;
    }

    properties.push({
      type: 'comment',
      value: 'Pinned by plugins/withArmV7aOnly.js — the target TV is 32-bit ARM only.',
    });
    properties.push({ type: 'property', key, value: 'armeabi-v7a' });
    return config;
  });

module.exports = withArmV7aOnly;
