package foundation.macha.tvinput

import android.app.Activity
import android.view.KeyEvent
import android.view.Window
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition

/**
 * Delivers remote keys to JavaScript by wrapping `Window.Callback`.
 *
 * Bridgeless React Native never emits `onHWKeyEvent`, and `JSKeyDispatcher`
 * drops keys unless an Android view holds focus, which the JS focus registry
 * never takes. The window callback is wrapped because `MainActivity` is
 * generated by `expo prebuild`.
 *
 * Back is not handled here: `BackHandler` can answer synchronously whether
 * JavaScript consumed it.
 */
class MachaTvInputModule : Module() {

  private var patchedWindow: Window? = null
  private var originalCallback: Window.Callback? = null

  override fun definition() = ModuleDefinition {
    Name("MachaTvInput")

    Events(EVENT_NAME)

    OnCreate { install(appContext.currentActivity) }

    // The activity is often absent at OnCreate. `install` is idempotent.
    OnActivityEntersForeground { install(appContext.currentActivity) }

    OnDestroy { uninstall() }
  }

  private fun install(activity: Activity?) {
    val window = activity?.window ?: return
    if (patchedWindow === window) return
    uninstall()

    val existing = window.callback ?: return
    originalCallback = existing
    patchedWindow = window
    window.callback = KeyInterceptingCallback(existing) { event -> handleKeyEvent(event) }
  }

  private fun uninstall() {
    val window = patchedWindow ?: return
    // Restore only a callback that is still ours; something may have wrapped it since.
    if (window.callback is KeyInterceptingCallback) {
      window.callback = originalCallback
    }
    patchedWindow = null
    originalCallback = null
  }

  /** True when this key belongs to the app and the platform should not also act on it. */
  private fun handleKeyEvent(event: KeyEvent): Boolean {
    val command = COMMANDS[event.keyCode] ?: return false

    // ACTION_DOWN only: `useTvNavigation` ignores the action, so emitting both
    // would move focus twice per press. `repeatCount` is passed so JavaScript
    // decides about held keys. ACTION_UP is still consumed below.
    if (event.action == KeyEvent.ACTION_DOWN) {
      sendEvent(
        EVENT_NAME,
        mapOf(
          "eventType" to command,
          "repeatCount" to event.repeatCount,
        ),
      )
    }

    return event.action == KeyEvent.ACTION_DOWN || event.action == KeyEvent.ACTION_UP
  }

  private class KeyInterceptingCallback(
    private val delegate: Window.Callback,
    private val onKey: (KeyEvent) -> Boolean,
  ) : Window.Callback by delegate {
    override fun dispatchKeyEvent(event: KeyEvent): Boolean =
      if (onKey(event)) true else delegate.dispatchKeyEvent(event)
  }

  private companion object {
    const val EVENT_NAME = "onTvKey"

    /**
     * Remote keys in the web client's command vocabulary. Remotes disagree on
     * whether OK sends Enter or D-pad centre, so `select` covers both.
     */
    val COMMANDS: Map<Int, String> =
      mapOf(
        KeyEvent.KEYCODE_DPAD_UP to "up",
        KeyEvent.KEYCODE_DPAD_DOWN to "down",
        KeyEvent.KEYCODE_DPAD_LEFT to "left",
        KeyEvent.KEYCODE_DPAD_RIGHT to "right",
        KeyEvent.KEYCODE_DPAD_CENTER to "select",
        KeyEvent.KEYCODE_ENTER to "select",
        KeyEvent.KEYCODE_NUMPAD_ENTER to "select",
        KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE to "playPause",
        KeyEvent.KEYCODE_MEDIA_PLAY to "playPause",
        KeyEvent.KEYCODE_MEDIA_PAUSE to "playPause",
        KeyEvent.KEYCODE_MEDIA_REWIND to "rewind",
        KeyEvent.KEYCODE_MEDIA_FAST_FORWARD to "fastForward",
        KeyEvent.KEYCODE_MEDIA_STOP to "stop",
        KeyEvent.KEYCODE_MEDIA_NEXT to "next",
        KeyEvent.KEYCODE_MEDIA_PREVIOUS to "previous",
      )
  }
}
