#!/usr/bin/env node
/**
 * Checks the version agrees everywhere Android and npm read it. Run by `pretest`.
 *
 * Android compares only `versionCode`, which Expo defaults to 1 when unset.
 * Derived as the phone client does:
 *
 *     major * 10000 + minor * 100 + patch      0.1.0 -> 100, 0.4.1 -> 401
 */
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (name) => JSON.parse(readFileSync(join(root, name), 'utf8'));

export function versionCodeFor(version) {
  const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(version);
  if (!match) throw new Error(`version is not bare semver: ${version}`);
  const [, major, minor, patch] = match.map(Number);
  if (minor > 99 || patch > 99) {
    // Two digits each: a 100th minor would collide with the next major.
    throw new Error(`minor and patch must each stay below 100: ${version}`);
  }
  return major * 10000 + minor * 100 + patch;
}

const pkg = read('package.json');
const app = read('app.json');
const expo = app.expo ?? app;

const problems = [];
if (expo.version !== pkg.version) {
  problems.push(`app.json version ${expo.version} does not match package.json ${pkg.version}`);
}

const expected = versionCodeFor(expo.version);
const actual = expo.android?.versionCode;
if (actual === undefined) {
  problems.push(`app.json has no android.versionCode — Expo would default it to 1, and every build would look identical to the device`);
} else if (actual !== expected) {
  problems.push(`android.versionCode is ${actual}, expected ${expected} for ${expo.version}`);
}

/**
 * `android/` is generated by `expo prebuild` and gitignored, so a bump in
 * `app.json` reaches an APK only after regenerating; the install-time check
 * cannot see a stale tree. Skipped when `android/` is absent (clean checkout).
 */
const gradle = join(root, 'android', 'app', 'build.gradle');
if (existsSync(gradle)) {
  const source = readFileSync(gradle, 'utf8');
  const code = /^\s*versionCode\s+(\d+)/m.exec(source)?.[1];
  const name = /^\s*versionName\s+"([^"]+)"/m.exec(source)?.[1];
  if (code === undefined || name === undefined) {
    problems.push('android/app/build.gradle states no versionCode/versionName to check');
  } else {
    if (Number(code) !== expected) {
      problems.push(
        `android/app/build.gradle has versionCode ${code}, expected ${expected}`
        + ' — run `npx expo prebuild --platform android` so the generated tree follows app.json',
      );
    }
    if (name !== expo.version) {
      problems.push(`android/app/build.gradle has versionName ${name}, expected ${expo.version}`);
    }
  }
}

/**
 * The README carries `_v<version>_` on the first line under its title; a
 * version quoted further down neither satisfies nor trips this.
 */
const readme = readFileSync(join(root, 'README.md'), 'utf8').split('\n');
const titleAt = readme.findIndex((line) => line.startsWith('# '));
const underTitle = readme.slice(titleAt + 1).find((line) => line.trim() !== '');
const wanted = `_v${pkg.version}_`;
if (titleAt < 0 || underTitle?.trim() !== wanted) {
  problems.push(
    `README.md should carry ${wanted} as the first line under its title; found ${JSON.stringify(underTitle ?? '')}`,
  );
}

if (problems.length > 0) {
  console.error('version-check: inconsistent version\n  ' + problems.join('\n  '));
  process.exit(1);
}

console.log(`version-check: ${expo.version} (versionCode ${expected}) consistent, config and generated tree.`);
